Some pages are now accessible without logging in
VerveTeam/Travelify pull request #2
Opened 2024-09-16 19:00 UTC by rangelkoli

Home, FAQ and Login pages can be viewed without loggin in

+ Changed the name of the webiste from React + Vite to Travelify

2024-09-16 19:27 UTC, gideon-harpanahalli commented on frugaloo/src/App.jsx
> +  // if (!session) {
If we dont need this code maybe we can remove this

2024-09-16 19:30 UTC, gideon-harpanahalli commented on frugaloo/src/components/Login.jsx
> +const supabase = createClient(
Would it be possible to get it from env vars

2024-09-16 19:30 UTC, gideon-harpanahalli commented on frugaloo/src/components/Navbar.jsx
> +  "https://srqijewflsvgaffwybfj.supabase.co/",
Here as well, if we can get it from env vars would be great!

2024-09-16 20:00 UTC, hemant-mistry commented
@rangelkoli Can we have the popups/tooltip [whatever suits in this case] for the **Add Itinerary button** as well the **Get Started** when the user tries to make an itinerary before logging in?

![image](https://github.com/user-attachments/assets/126771b6-49f5-4f7b-bba7-34b3ccea49db)

2024-09-16 20:02 UTC, hemant-mistry requested changes

2024-09-16 20:04 UTC, hemant-mistry reviewed
Updated the comments

2024-09-17 13:01 UTC, hemant-mistry reviewed
Updated with comments

2024-09-17 18:24 UTC, rangelkoli commented
> @rangelkoli Can we have the popups/tooltip [whatever suits in this case] for the **Add Itinerary button** as well the **Get Started** when the user tries to make an itinerary before logging in?
> 
> ![image](https://private-user-images.githubusercontent.com/108870271/367913384-126771b6-49f5-4f7b-bba7-34b3ccea49db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTE2NjUsIm5iZiI6MTcyNjU5MTM2NSwicGF0aCI6Ii8xMDg4NzAyNzEvMzY3OTEzMzg0LTEyNjc3MWI2LTQ5ZjUtNGY3Yi1iYmE3LTM0YjNjY2VhNDlkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNjQyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWQ0OWU2OWJiMjgzYzhlMTYzZmMzOTdmNjU0ZTJlN2EyNmYxM2QzNDYyMDlhZmFkZjJhZDQ4MmZjNTNmNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.54ZVUjqGph53dyWarb3xCZ0-Ug1nAtSMqQYZAe-TpEM)

![image](https://github.com/user-attachments/assets/e4d642f1-c990-414f-91b0-03e907972592)
Isnt there already a tooltip for the components on the Navbar, Plus what tooltip would be used for Get Started

2024-10-01 10:24 UTC, gideon-harpanahalli approved these changes
LG

2024-10-15 21:15 UTC, closed without merging